---
# Handler to restart Squid service
- name: restart squid
  service:
    name: squid
    state: restarted

# Handler to reload firewall
- name: reload firewalld
  service:
    name: firewalld
    state: reloaded 