#!/bin/bash

# Source common functions and configuration
source "$(dirname "$0")/../../lib/functions.sh"
source "$(dirname "$0")/../../lib/config.sh"

# Load configs
load_component_config "network" 2>/dev/null || true
load_component_config "warewulf" 2>/dev/null || true
load_component_config "slurm" 2>/dev/null || true
export_config

check_root

# Configure SLURM
configure_slurm() {
    info "Configuring SLURM..."
    
    # Backup existing configuration
    backup_file "/etc/slurm/slurm.conf"
    
    # Create new configuration
    cat > "/etc/slurm/slurm.conf" << 'EOF'
# Generated by Mini-HPC Setup
ClusterName=mini-hpc
SlurmUser=slurm
SlurmctldHost=localhost
AuthType=auth/munge
StateSaveLocation=/var/spool/slurm/state
SlurmctldLogFile=/var/log/slurm/slurmctld.log
SlurmdLogFile=/var/log/slurm/slurmd.log
Prolog=/etc/slurm/prolog.sh
Epilog=/etc/slurm/epilog.sh
SelectType=select/cons_tres

# CPU nodes (managed by Warewulf)
NodeName=cpu[01-03] CPUs=8 RealMemory=32000 State=UNKNOWN
PartitionName=cpu Nodes=cpu[01-03] Default=YES MaxTime=INFINITE State=UP

# GPU node (Jetson Orin Nano)
NodeName=gpu01 Gres=gpu:1 Sockets=1 CoresPerSocket=6 ThreadsPerCore=1 RealMemory=16000 State=UNKNOWN
PartitionName=gpu Nodes=gpu01 Default=NO MaxTime=INFINITE State=UP
EOF

    # Create prolog and epilog scripts
    create_prolog_epilog
}

# Create prolog and epilog scripts
create_prolog_epilog() {
    info "Creating prolog and epilog scripts..."
    
    # Create prolog script
    cat > "/etc/slurm/prolog.sh" << 'EOF'
#!/bin/bash
# Prolog script for SLURM jobs
exit 0
EOF
    chmod +x "/etc/slurm/prolog.sh"
    
    # Create epilog script
    cat > "/etc/slurm/epilog.sh" << 'EOF'
#!/bin/bash
# Epilog script for SLURM jobs
exit 0
EOF
    chmod +x "/etc/slurm/epilog.sh"
}

# Configure Munge on compute nodes
configure_munge_compute_nodes() {
    info "Configuring Munge on compute nodes..."
    
    # Copy Munge key to compute nodes
    for node in "${COMPUTE_NODES[@]}"; do
        info "Configuring Munge on node $node..."
        
        # Create Munge directory on compute node
        remote_exec "$node" "mkdir -p /etc/munge"
        
        # Copy Munge key
        scp /etc/munge/munge.key "root@$node:/etc/munge/munge.key"
        
        # Set permissions and start Munge
        remote_exec "$node" "chmod 400 /etc/munge/munge.key && systemctl enable --now munge"
    done
}

# Start SLURM services
start_slurm_services() {
    info "Starting SLURM services..."
    
    # Start slurmctld on head node
    start_service "slurmctld"
    
    # Start slurmd on all nodes -> start slurmd only on cpu nodes
    # start_service "slurmd"
}

# Main execution
main() {
    ensure_dir "$LOG_DIR"
    
    # Configure SLURM
    configure_slurm
    
    # Configure Munge on compute nodes
    configure_munge_compute_nodes
    
    # Start services
    start_slurm_services
    
    info "SLURM configuration completed successfully"
}

main "$@" 