#!/bin/bash

# Source common functions and configuration
source "$(dirname "$0")/../../lib/functions.sh"
source "$(dirname "$0")/../../lib/config.sh"

# Load configs
load_component_config "network" 2>/dev/null || true
load_component_config "warewulf" 2>/dev/null || true
load_component_config "slurm" 2>/dev/null || true
export_config

check_root

# Configure SLURM
configure_slurm() {
    info "Configuring SLURM..."

    local cpu_nodelist="${SLURM_CPU_NODELIST:-cpu[01-03]}"
    local cpu_cpus="${SLURM_CPU_CPUS:-8}"
    local cpu_sockets="${SLURM_SOCKETS:-1}"
    local cpu_cores_per_socket="${SLURM_CORES_PER_SOCKET:-8}"
    local cpu_threads_per_core="${SLURM_THREADS_PER_CORE:-1}"
    local cpu_real_memory="${SLURM_DEFAULT_MEM:-32000}"
    local slurmctld_port="${SLURMCTLD_PORT:-6817}"
    local slurmd_port="${SLURMD_PORT:-6818}"
    local srun_port_range="${SLURM_SRUN_PORT_RANGE:-60001-63000}"
    
    # Backup existing configuration
    backup_file "/etc/slurm/slurm.conf"
    
    # Create new configuration
    cat > "/etc/slurm/slurm.conf" << EOF
# Generated by Mini-HPC Setup
ClusterName=mini-hpc
SlurmUser=slurm
SlurmctldHost=${HEAD_NODE_HOSTNAME}(${HEAD_NODE_IP})
SlurmctldPort=${slurmctld_port}
SlurmdPort=${slurmd_port}
SrunPortRange=${srun_port_range}
AuthType=auth/munge
StateSaveLocation=/var/spool/slurm/state
SlurmctldLogFile=/var/log/slurm/slurmctld.log
SlurmdLogFile=/var/log/slurm/slurmd.log
Prolog=/etc/slurm/prolog.sh
Epilog=/etc/slurm/epilog.sh
SelectType=select/cons_tres

# CPU nodes
NodeName=${cpu_nodelist} CPUs=${cpu_cpus} Sockets=${cpu_sockets} CoresPerSocket=${cpu_cores_per_socket} ThreadsPerCore=${cpu_threads_per_core} RealMemory=${cpu_real_memory} State=UNKNOWN
PartitionName=cpu Nodes=${cpu_nodelist} Default=YES MaxTime=INFINITE State=UP
EOF

    if [ "${SLURM_GPU_ENABLED:-false}" = true ]; then
        cat >> "/etc/slurm/slurm.conf" << EOF
# GPU node
NodeName=${SLURM_GPU_NODELIST:-gpu01} Gres=${SLURM_GPU_GRES:-gpu:1} CPUs=${SLURM_GPU_CPUS:-6} RealMemory=${SLURM_GPU_MEM:-16000} State=UNKNOWN
PartitionName=gpu Nodes=${SLURM_GPU_NODELIST:-gpu01} Default=NO MaxTime=INFINITE State=UP
EOF
    fi

    # Create prolog and epilog scripts
    create_prolog_epilog
}

# Create prolog and epilog scripts
create_prolog_epilog() {
    info "Creating prolog and epilog scripts..."
    
    # Create prolog script
    cat > "/etc/slurm/prolog.sh" << 'EOF'
#!/bin/bash
# Prolog script for SLURM jobs
exit 0
EOF
    chmod +x "/etc/slurm/prolog.sh"
    
    # Create epilog script
    cat > "/etc/slurm/epilog.sh" << 'EOF'
#!/bin/bash
# Epilog script for SLURM jobs
exit 0
EOF
    chmod +x "/etc/slurm/epilog.sh"
}

# Configure firewalld for SLURM traffic
configure_slurm_firewall() {
    if [ "${FIREWALL_ENABLED:-true}" != "true" ]; then
        info "Firewall configuration is disabled"
        return 0
    fi

    if ! command -v firewall-cmd >/dev/null 2>&1; then
        warn "firewall-cmd not found; skipping SLURM firewall configuration"
        return 0
    fi

    if ! systemctl is-active --quiet firewalld; then
        warn "firewalld is not active; skipping SLURM firewall configuration"
        return 0
    fi

    local slurm_ports=(
        "${SLURMCTLD_PORT:-6817}"
        "${SLURMD_PORT:-6818}"
        "${SLURM_SRUN_PORT_RANGE:-60001-63000}"
    )
    local port

    info "Configuring firewall for SLURM ports..."
    for port in "${slurm_ports[@]}"; do
        info "Adding SLURM port to firewall: ${port}/tcp"
        firewall-cmd --permanent --add-port="${port}/tcp" || {
            error "Failed to configure firewall for SLURM port: $port"
            return 1
        }
    done

    firewall-cmd --reload || {
        error "Failed to reload firewall after SLURM port changes"
        return 1
    }
}

# Configure Munge on compute nodes
configure_munge_compute_nodes() {
    info "Configuring Munge on compute nodes..."
    
    # Copy Munge key to compute nodes
    for node in "${COMPUTE_NODES[@]}"; do
        info "Configuring Munge on node $node..."
        
        # Create Munge directory on compute node
        remote_exec "$node" "mkdir -p /etc/munge"
        
        # Copy Munge key
        scp /etc/munge/munge.key "root@$node:/etc/munge/munge.key"
        
        # Set permissions and start Munge
        remote_exec "$node" "chmod 400 /etc/munge/munge.key && systemctl enable --now munge"
    done
}

# Start SLURM services
start_slurm_services() {
    info "Starting SLURM services..."
    
    # Start slurmctld on head node
    start_service "slurmctld"
    
    # Start slurmd on all nodes -> start slurmd only on cpu nodes
    # start_service "slurmd"
}

# Main execution
main() {
    ensure_dir "$LOG_DIR"
    
    # Configure SLURM
    configure_slurm

    # Configure firewall for SLURM traffic
    configure_slurm_firewall
    
    # Configure Munge on compute nodes
    configure_munge_compute_nodes
    
    # Start services
    start_slurm_services
    
    info "SLURM configuration completed successfully"
}

main "$@"
