---
spack_version: v0.23.1
spack_commit: 2bfcc69fa870d3c6919be87593f22647981b648a
spack_build_user: hpc-spack
spack_repo: https://github.com/spack/spack.git
spack_install_dir: /opt/spack
spack_environment_dir: "{{ spack_install_dir }}/environments/hpc"
spack_view_dir: "{{ spack_install_dir }}/views/hpc"
spack_packages: [hdf5]
spack_build_jobs: 4
spack_verify_command: [h5dump, -V]
spack_verify_spec: "{{ spack_packages | first }}"
spack_command_environment:
  SPACK_DISABLE_LOCAL_CONFIG: 'true'
  SPACK_USER_CACHE_PATH: /var/cache/hpc-spack
  SPACK_PYTHON: /usr/bin/python3
