# Network Configuration
NETWORK_INTERFACE="enp2s0"
HEAD_NODE_IP="10.0.0.1"
NETWORK_MASK="255.255.252.0"
NETWORK="10.0.0.0"
DHCP_START="10.0.1.1"
DHCP_END="10.0.1.255"

# Firewall Configuration
FIREWALL_ENABLED=true
FIREWALL_SERVICES=("dhcp" "tftp" "nfs")
FIREWALL_PORTS=("9873")  # Warewulf port 