---
- name: Deploy ELK Stack
  hosts: monitoring
  become: true
  roles:
    - components/elk

- name: Deploy Grafana
  hosts: monitoring
  become: true
  roles:
    - components/grafana

- name: Configure Filebeat on compute nodes
  hosts: compute
  become: true
  roles:
    - components/filebeat
