---
- name: Deploy ELK Stack
  hosts: monitoring
  become: true
  roles:
    - elk

- name: Deploy Grafana
  hosts: monitoring
  become: true
  roles:
    - grafana

- name: Configure Filebeat on compute nodes
  hosts: compute
  become: true
  roles:
    - filebeat 