---
setup_security_defaults:
  firewall:
    manage: true
  selinux:
    manage: true
    state: enforcing
  audit:
    manage: true
    rules:
      - "-a always,exit -F arch=b64 -S execve -k commands"
      - "-w /etc/passwd -p wa -k identity"
      - "-w /etc/group -p wa -k identity"
      - "-w /etc/shadow -p wa -k identity"
      - "-w /etc/sudoers -p wa -k identity"
