---
- name: Warewulf restart daemon
  ansible.builtin.systemd:
    name: warewulfd
    state: restarted
- name: Warewulf restart chrony
  ansible.builtin.systemd:
    name: chronyd
    state: restarted
- name: Warewulf reload exports
  ansible.builtin.command:
    argv: [exportfs, -ra]
  changed_when: true
